// <auto-generated />
namespace VidyanoApplication2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class melding2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(melding2));
        
        string IMigrationMetadata.Id
        {
            get { return "202003031517591_melding2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
